# Configuración Global
spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          search-paths: 
            - 'config/global'
            - 'config/services/{application}'
            - 'config/{profile}'

# Configuración Base RabbitMQ
rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER:guest}
  password: ${RABBITMQ_PASS:guest}

# Configuración de Seguridad (Placeholders)
security:
  config-repo:
    username: ${CONFIG_REPO_USER:}
    password: ${CONFIG_REPO_PASS:}
