# Configuración Global
spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/Dvmc13/dynamic-resilience.git
          default-label: main 
          search-paths: 
            - 'config/global'
            - 'config/services/{application}'
            - 'config/{profile}'
          force-pull: true # Forzar siempre última versión

# Configuración Base RabbitMQ
rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER:guest}
  password: ${RABBITMQ_PASS:guest}

# Configuración de Seguridad (Placeholders)
security:
  config-repo:
    username: ${CONFIG_REPO_USER:}
    password: ${CONFIG_REPO_PASS:}
