spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    inetutils:
      preferredNetworks: 127.0.0.1
      ignoredInterfaces: eth0

spring:
  application:
    name: global-config  # O define el nombre de la aplicación en este archivo si lo deseas
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    prometheus:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      "*":
        metrics:
          enabled: true
  retry:
    instances:
      "*":
        metrics:
          enabled: true
  bulkhead:
    instances:
      "*":
        metrics:
          enabled: true
  ratelimiter:
    instances:
      "*":
        metrics:
          enabled: true

logging:
  level:
    root: INFO
    com.example.resilience_library: DEBUG
