spring:
  application:
    name: resilience-library

resilience:
  monitor:
    interval: 20s
  patterns:
    enabled: true

  services:
    - name: catalog-service
      host: localhost
      port: 8081

    - name: order-service
      host: localhost
      port: 8082
