global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'resilience-webhook'

receivers:
  - name: 'resilience-webhook'
    webhook_configs:
      - url: 'http://${GATEWAY_HOST:resilience-library}:${GATEWAY_PORT:8080}/webhook/alert'
        send_resolved: true
