global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'resilience-webhook'
  routes:
    - match:
        severity: critical
      receiver: 'resilience-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'resilience-webhook'

receivers:
  - name: 'resilience-webhook'
    webhook_configs:
      - url: 'http://${GATEWAY_HOST:resilience-library}:${GATEWAY_PORT:8080}/webhook/alert'
        send_resolved: true
        http_config:
          timeout: 5s
  
  - name: 'resilience-critical'
    email_configs:
      - to: 'admin@example.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://${GATEWAY_HOST:resilience-library}:${GATEWAY_PORT:8080}/webhook/critical'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
