resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 100ms
        register-health-indicator: true
    instances:
      default:
        base-config: default
      frontend:
        limit-for-period: 30
        limit-refresh-period: 1s
        timeout-duration: 200ms
        register-health-indicator: true

spring:
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@userKeyResolver}"
            redis-rate-limiter.replenish-rate: 50
            redis-rate-limiter.burst-capacity: 100

management:
  health:
    ratelimiters:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
