profiles:
  clients:
    - type: "mobile"
      maxRequestsPerMinute: 100
      timeout: 2000
      retry:
        maxAttempts: 3
        waitDuration: 500
      circuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 2000
        waitDurationInOpenState: 5000

    - type: "web"
      maxRequestsPerMinute: 500
      timeout: 5000
      retry:
        maxAttempts: 5
        waitDuration: 1000
      circuitBreaker:
        failureRateThreshold: 40
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        waitDurationInOpenState: 10000

    - type: "api"
      maxRequestsPerMinute: 1000
      timeout: 10000
      retry:
        maxAttempts: 2
        waitDuration: 300
      circuitBreaker:
        failureRateThreshold: 30
        slowCallRateThreshold: 40
        slowCallDurationThreshold: 5000
        waitDurationInOpenState: 15000
